name: englishapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
 
module:
  androidX: true

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_sequence_animation: "^3.0.0"
  flutter_facebook_login: ^3.0.0
  simple_animations: ^1.3.3
  share: ^0.6.0+1
  shared_preferences: ^0.5.6
  path_provider: ^0.4.1
  firebase_auth: ^0.15.4
  firebase_core: ^0.4.3+3
  google_sign_in: ^4.4.0
  get_it: ^3.1.0
  provider: ^4.0.4
  cloud_firestore: ^0.13.2+3
  random_string: ^2.0.1
  cupertino_icons: ^0.1.2
  rflutter_alert: ^1.0.3
  material_design_icons_flutter: ^3.2.4495

  flutter:
    sdk: flutter
  http: ^0.12.0 
  frideos: ^0.6.0
  font_awesome_flutter: ^8.4.0


  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  
  
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: yazi
      fonts:
        - asset: fonts/Rubik-Medium.ttf
    - family: Quicksand
      fonts:
        - asset: assets/Quicksand-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
      
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - images/
   - images/globemojies/
   - images/globemojies/
   - images/helpicons/
   - res/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
url_launcher: ^ 5.0.2
